SELECT DISTINCT(I.ITEM_ID), I.ITEM_NAME
FROM ITEM_INFO AS I
WHERE I.ITEM_ID IN (SELECT T.ITEM_ID
                 FROM ITEM_TREE AS T
                 WHERE T.PARENT_ITEM_ID IS NULL)
ORDER BY I.ITEM_ID